<a href="https://colab.research.google.com/github/SonnyCatt/COEN281-Data-Mining/blob/main/hw0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Define A and y

In [ ]:
import numpy as np

A = np.matrix('1 4;2 3')
y = np.matrix('1;3')
print(A)
print(y)

[[1 4]
 [2 3]]
[[1]
 [3]]


#Compute 𝑨𝑦 and 𝑦𝑨 

In [ ]:
multi_res1 = np.dot(A, y)
print(multi_res1)

[[13]
 [11]]


#What is a rank of a matrix? What is the rank of 𝑨?

In [ ]:
from numpy.linalg import matrix_rank
rank = matrix_rank(A)
print(rank)

2


#Manually compute the inverse of 𝑨, that is, 𝑨−𝟏. Compute 𝑨𝑨−𝟏 to check your answer. 


In [ ]:
print (np.linalg.inv(A))

[[-0.6  0.8]
 [ 0.4 -0.2]]


#Manually compute the eigenvectors and eigenvalues of 𝑨#

In [ ]:
b, c = np.linalg.eig(A)
print(b)
print(c)

[-1.  5.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


#Compute the projection of vector 𝑎  on to vector 𝑏 

In [ ]:
# import numpy to perform operations on vector
import numpy as np
  
a = np.array([1, 2])  
b = np.array([2, 1])   
  
# Task: Project vector u on vector v
  
# finding norm of the vector v
b_norm = np.sqrt(sum(b**2))    
  
# Apply the formula as mentioned above
# for projecting a vector onto another vector
# find dot product using np.dot()
proj = (np.dot(a, b)/b_norm**2)*b

print(proj)

[1.6 0.8]
